version: 2

sources:
  - name: staging
    database:
      dataengg-zoomcamp
      # For postgres:
      #database: production
    schema:
      trips_data_all

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
